runtime:
  cache_dir: ./.cache/antora

site:
  title: Nookbag example
  url: http://localhost:3000
  start_page: nookbag_base::index.adoc

content:
  sources:
    - url: .
      start_path: lab
asciidoc:
  attributes:
    release-version: master
    page-pagination: true
ui:
  bundle:
    url: https://github.com/rhpds/nookbag-bundle/releases/download/v0.0.2/bundle.zip
    snapshot: true
output:
  dir: ./dist/gh-pages
