showroom_version: HEAD
showroom_name: nookbag_base
antora_dir: antora
showroom_modules:
  - name: index
    label: 'Welcome to the Showroom UI/UX Demo and Playground'
    validation_script: ./validation-index.sh
  - name: module-1
    label: 'Module 1: Setup'
  - name: module-2
    label: 'Module 2: Deploy Service'
  - name: module-3
    label: 'Module 3: Test your skills'
  - name: EXTRA-MODULE/index
    label: 'Module Extra'

showroom_services:
  - name: double_terminal
    port: 8001
    secondary_port: 8002
    path: /wetty
    secondary_path: /wetty
  - name: codeserver
    port: 8003
  - name: docs
    url: https://docs.ansible.com/
