showroom_version: HEAD

showroom_modules:
  - index
  - module-1
  - module-2
  - module-3
  - EXTRA-MODULE/index

showroom_services:
  - double_terminal
  - codeserver
  - docs: https://docs.ansible.com/