showroom_version: HEAD
showroom_name: nookbag_base
antora_dir: antora
showroom_modules:
  - index
  - module-1
  - module-2
  - module-3
  - EXTRA-MODULE/index

showroom_services:
  - name: double_terminal
    port: 8001
    secondary_port: 8002
    path: /wetty
    secondary_path: 
  - name: codeserver
    port: 8003
  - name: docs
    url: https://docs.ansible.com/
